/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Game__factory } from "./Game__factory";
export { GameGateway__factory } from "./GameGateway__factory";
