/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Game } from "./Game";
export type { GameGateway } from "./GameGateway";
export * as factories from "./factories";
export { Game__factory } from "./factories/Game__factory";
export { GameGateway__factory } from "./factories/GameGateway__factory";
